# Generated by Django 5.2.4 on 2025-09-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_seller_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_img',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
