# Generated by Django 5.2.4 on 2025-09-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_seller_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
