# Generated by Django 5.1.7 on 2025-08-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_client_birth_date_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='county_of_origin',
            new_name='country_of_origin',
        ),
    ]
