# Generated by Django 5.1.7 on 2025-08-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_county_of_origin_client_country_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
            ],
        ),
    ]
